### ISSUE TITLE
Database Error in model stg_exposure_relationships

### ISSUE THREAD

**Issue by Lorenitz** [dbt-labs/dbt-project-evaluator#145]
### Describe the bug
Error message when executing the command:
`dbt build --select package:dbt_project_evaluator`

### Steps to reproduce
`dbt build --select package:dbt_project_evaluator`

### Actual results

Completed Succesfully

### Screenshots and log output
![Screenshot 2022-06-19 at 21 45 46](https://user-images.githubusercontent.com/31211443/174497920-3539157e-4ea7-4496-8027-c40f7ded5eed.png)

### System information
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.5
  - package: tnightengale/dbt_meta_testing
    version: 0.3.5
  - package: Snowflake-Labs/dbt_constraints
    version: [">=0.3.0", "<0.4.0"]
  - git: "https://github.com/dbt-labs/dbt-project-evaluator.git"
    revision: v0.1.0
```

**Which database are you using dbt with?**
- [x] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.0
  - latest:    1.1.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 1.1.0 - Up to date!
  - postgres: 1.1.0 - Update available!
```
