### ISSUE TITLE
Allow relation tests in other directories

### ISSUE THREAD

**Issue by jelstongreen** [dbt-labs/dbt-project-evaluator#172]
### Describe the feature
Relationship tests between layers / directories currently fail the `fct_test_directories` test - these tests are often going to be comparing models that exist in other directories so should allow these comparisons. 

### Describe alternatives you've considered
I'm not aware of any. 

### Additional context
Not AFAIK

### Who will this benefit?
Anyone using multi layer projects with relationship tests. 

### Are you interested in contributing this feature?
I could do if needed

**Comment by jelstongreen** [comment]
As an example
- final
  - finance
    - fnl_finance_customerreturns.sql
    - schema.yml
- warehouse
  - wh_customers.sql
  - schema.yml

An entry in the  final/finance/schema.yml like:
```
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('wh_customers')
              field: customer_id
```
will fail the `fct_test_directories` test as `wh_customers` is not in the same directory as the test.
