### ISSUE TITLE
SQL error when adding columns with SQL code

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-project-evaluator#185]
### Describe the bug

Raised by a user in the dbt Community Slack (Thanks!).

When adding columns with SQL code (allowed in dbt Core) to test them, they may raise errors when loading `stg_nodes`.

e.g. the following column name/test currently fails:
```
models:
  - name: stg_model_4
    columns:
      - name: "concat(coalesce(id,1),' - ','test_sql_column')"
        tests:
          - unique
```

### Expected results

The data should be loaded correctly
