### ISSUE TITLE
Optional change of severity for test: is_empty

### ISSUE THREAD

**Issue by Kratzbaum92** [dbt-labs/dbt-project-evaluator#190]
### Describe the feature
We would like to decide about the severity of the test: is_empty

Suggestion:

dbt_project.yml
tests:
  generic:
    test_is_empty:
      +severity: warn

we would override the severity with jinja 
pseudocode:

if SLIM_CI = true and model = X then 'error'
else 'warn

### Who will this benefit?
Customers who have implemented SLIM_CI and would like to add the dbt_project_evaluator tests to their acceptance criteria for a merge.

### Are you interested in contributing this feature?

Let us know if you want to contribute the feature, and whether would need a hand getting started
--->

**Comment by dave-connors-3** [comment]
hey @Kratzbaum92 ! Thanks so much for opening an issue!  We will definitely chat a bit about making the test configs more customizable. 

In the meantime I believe you may be able to achieve the behavior you're after just by altering your `dbt_project.yml` to add a tests config block like you have above. 

to change _all_ tests from this package to be `severity: error` you could add
```yml
tests:
  dbt_project_evaluator:
    +severity: error
```

If you wanted to change only those related to tests (i.e. `fct_missing_primary_keys` and `fct_test_coverage`, you could add:
```yml
tests:
  dbt_project_evaluator:
    marts:
      tests:
        +severity: error
```

The slight nuance here is that the path to the test will actually be the path to the yml definition of that test, which will follow the folder structure of the models directory. 

You could also as you mention use a macro here to be environment specific and change the severity based on the environment you're running in:
```yml
tests:
  dbt_project_evaluator:
    marts:
      tests:
        +severity: "{{ 'error' if target.name == 'CI' else 'warn' }}"
```
