### ISSUE TITLE
Loosen dependency requirements in `packages.yml`

### ISSUE THREAD

**Issue by waligob** [dbt-labs/dbt-project-evaluator#198]
### Describe the feature
Providing a range of supported package versions for `dbt_utils` would allow for `dbt_project_evaluator` to be installed alongside other packages much more easily. Currently, `dbt_project_evaluator` is [pinned to the `0.8.6` patch version of `dbt_utils`](https://github.com/dbt-labs/dbt-project-evaluator/blob/8269c67c0fe13320e0cafd7d5c79c272621e546b/packages.yml#L2-L3), which heavily constrains the dependency graph of compatible package versions when installed in conjunction with other packages.

### Describe alternatives you've considered
The alternative is to only install `dbt_project_evaluator` alongside packages that are compatible with the pinned patch versions. 

### Additional context
N/A

### Who will this benefit?
Users who are attempting to update their dbt packages on a regular cadence in order to adopt the latest features and bugfixes.

### Are you interested in contributing this feature?
I haven't contributed before. I would be happy to help, but I would need a hand getting started.

**Comment by dave-connors-3** [comment]
hey @waligob! thanks for opening an issue here. 

I think this is a reasonable ask! Can you say a bit more about the specific issues you're seeing in your current deployment? Is this versioning specifically causing issues with a direct install of dbt_utils, or is there another package with a different dependency on utils that is causing an issue?

In any case, I'll see if there's any prior art on how to handle package dependencies and will look into loosening the requirement!

**Comment by dave-connors-3** [comment]
After a bit more research, we have a few macros in this package that were released in dbt_utils `v.0.8.6`, so that will need to be our floor regardless!

**Comment by waligob** [comment]
Thanks @dave-connors-3. Here is our current `dbt_packages.yml`

```yml

packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.8.6", "<0.9.0"]
  - package: calogica/dbt_expectations
    version: [">=0.5.8", "<0.6.0"]
  - package: dbt-labs/metrics
    version: [">=0.3.1","<0.4.0"]
  - package: dbt-labs/dbt_project_evaluator
    version: 0.1.1
``` 

* `dbt-labs/dbt_utils` is currently on the `0.9.1` [release](https://github.com/dbt-labs/dbt-utils/releases)
* `calogica/dbt_expectations` is currently on the `0.6.0` [release](https://github.com/calogica/dbt-expectations/releases)
    * this package requires `calogica/dbt_date[">=0.6.0", "<0.7.0"]`, which in turn requires `dbt-labs/dbt_utils[">=0.9.0", "<1.0.0"]`

So, currently, we can't upgrade to the latest minor versions of `calogica/dbt_expectations` or `dbt-labs/dbt_utils`.
