### ISSUE TITLE
Dependency issue with dbt/utils

### ISSUE THREAD

**Issue by raajpackt** [dbt-labs/dbt-project-evaluator#253]
### Description
This occured while running `dbt deps` to install the package

Error trace : 

![image](https://user-images.githubusercontent.com/68896091/206104327-3fbfe6ba-a840-43e9-b336-10d89af8c479.png)

### Steps to reproduce
The following is what is in my `package.yml` file
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.0
  - package: data-mie/dbt_profiler
    version: 0.3.0
  - package: dbt-labs/redshift
    version: 0.6.1
  - package: dbt-labs/codegen
    version: 0.7.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.2.1
```

I tried bumping up the version of `dbt-utils` to v1 but still did not work. Is there any other version of dbt-project-evaluator which could work with my requirements?
