### ISSUE TITLE
Can't install with dbt_utils==1.0.0

### ISSUE THREAD

**Issue by Jonathan-MW** [dbt-labs/dbt-project-evaluator#263]
### Describe the bug
Can't install with dbt_utils==1.0.0. We can't revert to a lower version of dbt_utils, as the new "generate_surrogate_key" macro is used throughout the repo, instead of the deprecated "surrogate_key" macro of dbt_utils.

### Steps to reproduce
- Add the lines below to packages.yml
  ```
  package: dbt-labs/dbt_project_evaluator
  version: 0.2.1
  ```
- In dbt_project.yml, add the following config:
  ```
  dispatch:
    - macro_namespace: dbt_utils
      search_order: ['dbt_project_evaluator', 'spark_utils', 'dbt_utils']
  ```
- Run `dbt deps`

### Expected results
No error when when running: `dbt deps`

### Actual results
`dbt deps` gives error: 
Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['=1.0.0', '>=0.8.0', '<2.0.0', '>=0.8.6', '<1.0.0']

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/codegen
    version: 0.8.1
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.2.1
```

**Which database are you using dbt with?**
Databricks
dbt-databricks==1.3.2

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - databricks: 1.3.2 - Up to date!
  - spark:      1.3.0 - Up to date!
```
