### ISSUE TITLE
INSERT has more expressions than target columns

### ISSUE THREAD

**Issue by glsdown** [dbt-labs/dbt-project-evaluator#292]
### Describe the bug
@RAbramson1 @jared-rimmer and I, are currently in the process of upgrading from v0.2.1 to v0.4.0. When trying to build (after running `dbt clean && dbt deps`), we are getting an `INSERT has more expressions than target columns` error on some of the staging tables.

On investigating, it appears to be because we have materialised them as views, and the individual model configs to build them as tables is being ignored.

### Steps to reproduce
In our project file we have the following configuration

```yml
# dbt_project.yml
models:
  dbt_project_evaluator:
    +materialized: table
    +schema: dbt_project_evaluator
    marts:
      +enabled: false
    staging:
      +enabled: true
      # Default to views unless necessary for performance
      +materialized: view
    dispatch:
      - macro_namespace: dbt
        search_order: ['dbt_project_evaluator', 'dbt']
```

Then on attempting to build:

```
dbt build --select package:dbt_project_evaluator dbt_project_evaluator_exceptions
```

This is where we get the error message.

### Expected results
Models materialise as tables as expected, or there are explicit instructions around overwriting the materialisation of models.

### Actual results
Models build with no errors

### Screenshots and log output
```
01:34:11  Completed with 2 errors and 0 warnings:
01:34:11  
01:34:11  Database Error in model base_node_relationships (models/staging/graph/base/base_node_relationships.sql)
01:34:11    INSERT has more expressions than target columns
01:34:11    compiled Code at target/run/dbt_project_evaluator/models/staging/graph/base/base_node_relationships.sql
01:34:11  
01:34:11  Database Error in model stg_sources (models/staging/graph/stg_sources.sql)
01:34:11    INSERT has more expressions than target columns
01:34:11    compiled Code at target/run/dbt_project_evaluator/models/staging/graph/stg_sources.sql
```

### System information
**The contents of your `packages.yml` file:**
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.4.0
  - package: elementary-data/elementary
    version: 0.6.12
  - package: calogica/dbt_date
    version: [">=0.7.0", "<0.8.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.4.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 1.3.0 - Update available!
  - postgres: 1.3.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional context
Updating out `dbt_project.yml` file to materialise these as `table` instead of `view` appears to resolve the issue.

**Comment by dave-connors-3** [comment]
hey @glsdown -- thanks for opening the issue!

As of `v0.4.0`, these staging models use a `INSERT` statement as a post hook to populate the values to prevent massive SQL statements from throwing errors on very large dbt projects using this package. This means that these staging models _**must be materialized as tables**_. As you noted, removing that override should resolve the issue!

As an aside, it looks like you may have your `dispatch` config nested under your `models` config in the above `dbt_project.yml` sample code. Definitely make sure those are separated into two top-level configs!

```yml
# dbt_project.yml
models:
  dbt_project_evaluator:
    +materialized: table
    +schema: dbt_project_evaluator
    marts:
      +enabled: false
    staging:
      +enabled: true
      # Default to views unless necessary for performance
      +materialized: view

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']
```
