### ISSUE TITLE
Redshift shim type_string not being called

### ISSUE THREAD

**Issue by RAbramson1** [dbt-labs/dbt-project-evaluator#293]
### Describe the bug
@rsanjabi,  @dluftspring, and I are currently in the process of upgrading from v0.2.1 to v0.4.0. When trying to build, it appears that the `redshift__type_string` macro is not getting called appropriately; instead, the `type_string` macro appears in its place.
 
### Steps to reproduce
Paste the following in your dbt_project.yml:
```
    dispatch:
      - macro_namespace: dbt
        search_order: ['dbt_project_evaluator', 'dbt']
```

Then on attempting to build:

```
dbt build --select package:dbt_project_evaluator dbt_project_evaluator_exceptions
```

We run into the following issue: 

```
Postgres adapter: Postgres error: value too long for type character varying(1)
```

The compiled code looks like this: 

```
  create  table
   "dbt_raphaelaabramson_dbt_project_evaluator"."base_node_relationships__dbt_tmp"
    
    
    
  as (
    

/* Bigquery won't let us `where` without `from` so we use this workaround */
with dummy_cte as (
    select 1 as foo
) 

select 
    cast(null as TEXT) as resource_id,
    cast(null as TEXT) as direct_parent_id,
    cast(True as boolean) as is_primary_relationship

from dummy_cte
where false
  )
```

### Expected results
The compiled code should look like this: 
```
with 

_base_node_relationships as (
    select * from "dbt_raphaelaabramson_dbt_project_evaluator"."base_node_relationships"
),

final as (
    select 
        
    
md5(cast(coalesce(cast(resource_id as VARCHAR(600)), '') || '-' || coalesce(cast(direct_parent_id as VARCHAR(600)), '') as TEXT)) as unique_id, 
        *
    from _base_node_relationships
)

select  * from final
```

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.4.0
  - package: elementary-data/elementary
    version: 0.6.12
  - package: calogica/dbt_date
    version: [">=0.7.0", "<0.8.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.1
  - latest:    1.4.1 - Up to date!

Plugins:
  - redshift: 1.4.0 - Up to date!
  - postgres: 1.4.1 - Up to date!
```

### Additional context
When I add the the `redshift_shims` macro to my project the code compiles correctly.
