### ISSUE TITLE
add warning to `INSERT` models to make sure they are tables

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#298]
hey @glsdown -- thanks for opening the issue!

As of `v0.4.0`, these staging models use a `INSERT` statement as a post hook to populate the values to prevent massive SQL statements from throwing errors on very large dbt projects using this package. This means that these staging models _**must be materialized as tables**_. As you noted, removing that override should resolve the issue!

As an aside, it looks like you may have your `dispatch` config nested under your `models` config in the above `dbt_project.yml` sample code. Definitely make sure those are separated into two top-level configs!

```yml
# dbt_project.yml
models:
  dbt_project_evaluator:
    +materialized: table
    +schema: dbt_project_evaluator
    marts:
      +enabled: false
    staging:
      +enabled: true
      # Default to views unless necessary for performance
      +materialized: view

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']
```

_Originally posted by @dave-connors-3 in https://github.com/dbt-labs/dbt-project-evaluator/issues/292#issuecomment-1412303129_
