### ISSUE TITLE
`print_dbt_project_evaluator_issues` fails with Database Error "relation ___ does not exist"

### ISSUE THREAD

**Issue by mtilda** [dbt-labs/dbt-project-evaluator#337]
### Describe the bug

Following these [instructions](https://dbt-labs.github.io/dbt-project-evaluator/0.5/customization/issues-in-log/), I used the macro `print_dbt_project_evaluator_issues` in the property [`on-run-end`](https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end). At the end of running `dbt_project_evaluator`, I get unexpected errors (see "Actual results").
```yml
on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
```

### Steps to reproduce

My `dbt_project.yml` looks something like this:
```yml
config-version: 2

model-paths: ["models"]

vars:
  dbt_project_evaluator:
    staging_folder_name: bronze
    intermediate_folder_name: silver
    marts_folder_name: gold

models:
  dbt_project_evaluator:
    schema: dbt_project_evaluator

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
```

Run the command:
```bash
dbt build -s package:dbt_project_evaluator
```

### Expected results

I expect `dbt_project_evaluator` issues to show up in the console.

### Actual results

Fails with Database Error "relation ___ does not exist". The relation changes as I try to reproduce this, and I am not sure why. See logs below for specific messages.

When I check my database for the "missing" relation, I can see it exists and contains the data I would expect.

### Screenshots and log output

```
### List of issues raised by dbt_project_evaluator ###

-- is_empty_fct_model_directories_ --
20:30:36  Database error while running on-run-end
20:30:36  Encountered an error:
Database Error
  relation "fct_model_directories" does not exist
  LINE 3:         select * from fct_model_directories
                                ^
```

```
### List of issues raised by dbt_project_evaluator ###

-- is_empty_fct_marts_or_intermediate_dependent_on_source_ --
20:42:03  Database error while running on-run-end
20:42:03  Encountered an error:
Database Error
  relation "fct_marts_or_intermediate_dependent_on_source" does not exist
  LINE 3:         select * from fct_marts_or_intermediate_dependent_on...
                                ^
```

### System information
**The contents of your `packages.yml` file:**
```yml
packages:
  - package: dbt-labs/dbt_project_evaluator
    version: 0.4.1
  - package: dat/dbt_utils
    version: 1.0.0
  - package: calogica/dbt_date
    version: 0.7.2
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
  - package: EqualExperts/dbt_unit_testing
    version: 0.2.7
```

**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```
Core:
  - installed: 1.3.1
  - latest:    1.5.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 1.3.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional notes

One theory I have is that this macro is somehow querying the wrong schema (not aware of the property `models.dbt_project_evaluator.schema` in `dbt_project.yml`).

### Are you interested in contributing the fix?

Happy to create or review a PR, but I need help determining the root cause.
