### ISSUE TITLE
Models from excluded package not ignored in fct_model_directories.sql

### ISSUE THREAD

**Issue by dallmkp** [dbt-labs/dbt-project-evaluator#370]
### Describe the bug
I have included `get-select/dbt_snowflake_monitoring` as a module to my project. I have explicitly excluded it from being validated.  When running the project validator, it fails on `is_empty_fct_model_directories` test. I would expect that these files would be excluded

-- is_empty_fct_model_directories_ --
| RESOURCE_NAME                      | RESOURCE_TYPE | MODEL_TYPE | CURRENT_FILE_PATH                                     | CHANGE_FILE_PATH_TO                                                           |
| ---------------------------------- | ------------- | ---------- | ----------------------------------------------------- | ----------------------------------------------------------------------------- |
| stg_database_storage_usage_history | model         | staging    | models/staging/stg_database_storage_usage_history.sql | models/staging/snowflake_account_usage/stg_database_storage_usage_history.sql |
| stg_query_history                  | model         | staging    | models/staging/stg_query_history.sql                  | models/staging/snowflake_account_usage/stg_query_history.sql                  |
| stg_metering_history               | model         | staging    | models/staging/stg_metering_history.sql               | models/staging/snowflake_account_usage/stg_metering_history.sql               |
| stg_warehouse_metering_history     | model         | staging    | models/staging/stg_warehouse_metering_history.sql     | models/staging/snowflake_account_usage/stg_warehouse_metering_history.sql     |
| stg_remaining_balance_daily        | model         | staging    | models/staging/stg_remaining_balance_daily.sql        | models/staging/snowflake_organization_usage/stg_remaining_balance_daily.sql   |
| stg_access_history                 | model         | staging    | models/staging/stg_access_history.sql                 | models/staging/snowflake_account_usage/stg_access_history.sql                 |
| stg_metering_daily_history         | model         | staging    | models/staging/stg_metering_daily_history.sql         | models/staging/snowflake_account_usage/stg_metering_daily_history.sql         |
| stg_serverless_task_history        | model         | staging    | models/staging/stg_serverless_task_history.sql        | models/staging/snowflake_account_usage/stg_serverless_task_history.sql        |
| stg_warehouse_events_history       | model         | staging    | models/staging/stg_warehouse_events_history.sql       | models/staging/snowflake_account_usage/stg_warehouse_events_history.sql       |
| stg_rate_sheet_daily               | model         | staging    | models/staging/stg_rate_sheet_daily.sql               | models/staging/snowflake_organization_usage/stg_rate_sheet_daily.sql          |
| stg_stage_storage_usage_history    | model         | staging    | models/staging/stg_stage_storage_usage_history.sql    | models/staging/snowflake_account_usage/stg_stage_storage_usage_history.sql    |
| stg_usage_in_currency_daily        | model         | staging    | models/staging/stg_usage_in_currency_daily.sql        | models/staging/snowflake_organization_usage/stg_usage_in_currency_daily.sql   |

### Steps to reproduce
1. Add  get-select/dbt_snowflake_monitoring to packages.yaml 
```yaml
  # Snowflake budget monitoring
  - package: get-select/dbt_snowflake_monitoring
    version: [ ">=4.0.0", "<5.0.0" ]
```
2. Exclude it from dbt_project.yaml
```yaml
vars:
  # Exclude 3rd party packages from project evaluator
  exclude_packages: [ "dbt_snowflake_monitoring" ]
```
3. Install dependencies
```
dbt deps
``` 
4. Run the project validator
```bash
ENABLE_DBT_PROJECT_EVALUATOR=true DBT_PROJECT_EVALUATOR_SEVERITY=error dbt build -t ci  --select package:dbt_project_evaluator dbt_project_evaluator_exceptions
```

### Expected results
I should expect to see no errors from dbt_snowflake_monitoring project

### Actual results
-- is_empty_fct_model_directories_ --
| RESOURCE_NAME                      | RESOURCE_TYPE | MODEL_TYPE | CURRENT_FILE_PATH                                     | CHANGE_FILE_PATH_TO                                                           |
| ---------------------------------- | ------------- | ---------- | ----------------------------------------------------- | ----------------------------------------------------------------------------- |
| stg_database_storage_usage_history | model         | staging    | models/staging/stg_database_storage_usage_history.sql | models/staging/snowflake_account_usage/stg_database_storage_usage_history.sql |
| stg_query_history                  | model         | staging    | models/staging/stg_query_history.sql                  | models/staging/snowflake_account_usage/stg_query_history.sql                  |
| stg_metering_history               | model         | staging    | models/staging/stg_metering_history.sql               | models/staging/snowflake_account_usage/stg_metering_history.sql               |
| stg_warehouse_metering_history     | model         | staging    | models/staging/stg_warehouse_metering_history.sql     | models/staging/snowflake_account_usage/stg_warehouse_metering_history.sql     |
| stg_remaining_balance_daily        | model         | staging    | models/staging/stg_remaining_balance_daily.sql        | models/staging/snowflake_organization_usage/stg_remaining_balance_daily.sql   |
| stg_access_history                 | model         | staging    | models/staging/stg_access_history.sql                 | models/staging/snowflake_account_usage/stg_access_history.sql                 |
| stg_metering_daily_history         | model         | staging    | models/staging/stg_metering_daily_history.sql         | models/staging/snowflake_account_usage/stg_metering_daily_history.sql         |
| stg_serverless_task_history        | model         | staging    | models/staging/stg_serverless_task_history.sql        | models/staging/snowflake_account_usage/stg_serverless_task_history.sql        |
| stg_warehouse_events_history       | model         | staging    | models/staging/stg_warehouse_events_history.sql       | models/staging/snowflake_account_usage/stg_warehouse_events_history.sql       |
| stg_rate_sheet_daily               | model         | staging    | models/staging/stg_rate_sheet_daily.sql               | models/staging/snowflake_organization_usage/stg_rate_sheet_daily.sql          |
| stg_stage_storage_usage_history    | model         | staging    | models/staging/stg_stage_storage_usage_history.sql    | models/staging/snowflake_account_usage/stg_stage_storage_usage_history.sql    |
| stg_usage_in_currency_daily        | model         | staging    | models/staging/stg_usage_in_currency_daily.sql        | models/staging/snowflake_organization_usage/stg_usage_in_currency_daily.sql   |

### System information
**The contents of your `packages.yml` file:**
```yaml
packages:
  # External Libraries
  # Semi-required utils library
  - package: dbt-labs/dbt_utils
#    version: 1.1.1
    version: [">=1.0.0", "<2.0.0"]

  - package: Montreal-Analytics/snowflake_utils
    version: 0.5.0

  # Data testing library based on Great Expectations
  # Error installing because dbt_utils version mismatches
#  - package: calogica/dbt_expectations
#    version: [">=0.8.0", "<0.9.0"]

  # Unit testing library
  - git: "https://github.com/EqualExperts/dbt-unit-testing"
    revision: v0.2.6

  # Best practices enforcement
  - package: dbt-labs/dbt_project_evaluator
    version: [">=0.6.2", "<0.7.0"]

  # Observability tool
  - package: re-data/re_data
    version: [">=0.10.8", "<0.11.0"]

  # Snowflake budget monitoring
  - package: get-select/dbt_snowflake_monitoring
    version: [ ">=4.0.0", "<5.0.0" ]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt --version
Core:
  - installed: 1.5.4
  - latest:    1.6.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.5.2 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

```

### Are you interested in contributing the fix?
Yes, if its easy to do.

**Comment by dave-connors-3** [comment]
hey @dallmkp ! this looks like indeed a miss when we updated the exclusion logic! will get a bug fix out soon!

**Comment by dallmkp** [comment]
I tested this with 0.7.2 and received same error as before.

**Comment by dave-connors-3** [comment]
hey @dallmkp -- just to be sure, can you confirm the commands you ran to test this fix?

**Comment by dallmkp** [comment]
It looks like from #372 that you identified the error. I'll re-test with the next version when that gets released. Thanks for speedy resolution!

**Comment by dave-connors-3** [comment]
@dallmkp -- if you want to validate ahead of the release, we'd love a little extra reassurance!

```yml
packages:
  - git: "https://github.com/dbt-labs/dbt-project-evaluator.git"
    revision: main
```
