### ISSUE TITLE
Column counts not working!

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#379]
### Describe the bug

The columns that count the number of columns defined and described seem to be not working for the bigquery adapter:

for a given yml entry:

```
models:
  - name: report_1
    description: tom cruise's minority report
    access: public
    config:
      materialized: table
    columns:
      - name: col 
        description: col me maybe
        data_type: boolean
```

`dbt show --inline "select name, version, total_defined_columns, total_described_columns  from {{ ref('stg_nodes') }} where name ='report_1'" -t duckdb`

returns 

```
| name     | version | total_defined_col... | total_described_c... |
| -------- | ------- | -------------------- | -------------------- |
| report_1 |         |                    1 |                    0 |

```

This is the correct number of columns, incorrect number of described columns

`dbt show --inline "select name, version, total_defined_columns, total_described_columns  from {{ ref('stg_nodes') }} where name ='report_1'" -t bigquery`

returns 

```
| name     | version | total_defined_col... | total_described_c... |
| -------- | ------- | -------------------- | -------------------- |
| report_1 |         |                    0 |                    0 |
```

wrong on both counts!

### Steps to reproduce
1. create a model with column definitions
2. check `total_defined_columns` and `total_described_columns` in `stg_nodes` 
3. weep

### Expected results

output properly counts the number of defined and described columns!

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [x] duckdb
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```
