### ISSUE TITLE
Docs - Incorrect indentation in code snippets for the CI check docs

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-project-evaluator#429]
The snippets contain code like

```yaml
tests:
dbt_project_evaluator:
    +severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'warn') }}"
```

but it should be 

```yaml
tests:
  dbt_project_evaluator:
    +severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'warn') }}"
```
