### ISSUE TITLE
value too long for type character varying(600) when building new columns models

### ISSUE THREAD

**Issue by borismo** [dbt-labs/dbt-project-evaluator#437]
### Describe the bug
Two models introduced in [v0.9.0](https://github.com/dbt-labs/dbt-project-evaluator/releases/tag/v0.9.0) fail to build for us. More specifically they come from https://github.com/dbt-labs/dbt-project-evaluator/pull/386:
- `base_node_columns`
- `base_source_columns`

### Steps to reproduce
1. update package to v0.9.0
2. run `dbt deps`
3. run `dbt build --select package:dbt_project_evaluator`

### Expected results
I expect models to build successfully

### Actual results
Getting
```
02:12:33  Completed with 2 errors and 1 warning:
02:12:33
02:12:33    Database Error in model base_node_columns (models/staging/graph/base/base_node_columns.sql)
  value too long for type character varying(600)
  compiled Code at target/run/dbt_project_evaluator/models/staging/graph/base/base_node_columns.sql
02:12:33
02:12:33    Database Error in model base_source_columns (models/staging/graph/base/base_source_columns.sql)
  value too long for type character varying(600)
  compiled Code at target/run/dbt_project_evaluator/models/staging/graph/base/base_source_columns.sql
```

### System information
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: calogica/dbt_expectations
    version: 0.10.3
  - package: dbt-labs/dbt_external_tables
    version: 0.8.7
  - package: elementary-data/elementary
    version: 0.14.1
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: dbt-labs/dbt_project_evaluator
    version: 0.8.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.3
  - latest:    1.7.9 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 1.7.3 - Update available!
  - redshift: 1.7.3 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional context
Compiled code for `base_node_columns`:
```sql
with dummy_cte as (
    select 1 as foo
) 

select 
    cast(null as VARCHAR(600)) as node_unique_id,
    cast(null as VARCHAR(600)) as name,
    cast(null as VARCHAR(600)) as description,
    cast(null as VARCHAR(600)) as data_type,
    cast(null as VARCHAR(600)) as quote

from dummy_cte
where false
```
and obviously runs

### Are you interested in contributing the fix?
Yes, I would like to start with finding out what are the values that don't fit in a `VARCHAR(600)` but I don't know how.
