### ISSUE TITLE
Multiline column `description`s result in SQL errors

### ISSUE THREAD

**Issue by waligob** [dbt-labs/dbt-project-evaluator#448]
### Describe the bug

When columns have a multiline `description`, the `base_node_columns` and `base_source_columns` models fail to build due to a SQL error. 

### Steps to reproduce

We have a model config that looks like so:

```yml
version: 2
models:
  - name: int_ga360_hits_custom_fields_stage
    columns:
      - name: article_completions
        description: >
          Indicates whether the user completed an article. If so, then this
          column will contain 1 (otherwise null).
```

When running `dbt run --select base_node_columns`, the command fails with the following error:
```
18:18:14    Database Error in model base_node_columns (models/staging/graph/base/base_node_columns.sql)
  Syntax error: Unclosed string literal at [1025:1]
  compiled Code at target/run/dbt_project_evaluator/models/staging/graph/base/base_node_columns.sql
```

The compiled BigQuery statement illustrates that a line break in the `.yml` file is being propagated as a newline in the corresponding SQL `INSERT INTO` statement, leading to a SQL error.

<img width="847" alt="image" src="https://github.com/dbt-labs/dbt-project-evaluator/assets/93673562/8dae3f60-0925-4127-b0e5-157e9dcfeda4">

### Expected results

`dbt run --select base_node_columns` succeeds when a column has a multiline `description`

### Actual results

`dbt run --select base_node_columns` errors when a column has a multiline `description`

### System information
**The contents of your `packages.yml` file:**
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.1.0", "<1.2.0"]
  - package: calogica/dbt_expectations
    version: [">=0.10.0", "<0.11.0"]
  - package: dbt-labs/codegen
    version: [">=0.12.0", "<0.13.0"]
  - package: data-mie/dbt_profiler
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/dbt_project_evaluator
    version: [">=0.10.0", "<0.11.0"]
  - package: brooklyn-data/dbt_artifacts
    version: [">=2.6.0", "<2.7.0"]
  - package: elementary-data/elementary
    version: [">=0.14.0", "<0.15.0"]
  - package: dbt-labs/audit_helper
    version: [">=0.9.0", "<1.0.0"]
  - package: grafana/leaner_query
    version: [">=0.1.12", "<0.2.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
18:26:25  Running with dbt=1.7.10
18:26:26  Registered adapter: bigquery=1.7.7
```

### Additional context

`base_source_columns` also fails under the same conditions

### Are you interested in contributing the fix?

Sure! I would need a hand
