### ISSUE TITLE
dbt run  --select=package:dbt_project_evaluator fails

### ISSUE THREAD

**Issue by nickagel** [dbt-labs/dbt-project-evaluator#480]
### Describe the bug
dbt run  --select=package:dbt_project_evaluator fails. I'm using redshift and getting a 
 Database Error in model stg_nodes (models/staging/graph/stg_nodes.sql)
  value too long for type character varying(600)
  compiled Code at target/run/dbt_project_evaluator/models/staging/graph/stg_nodes.sql

```
dispatch:
  - macro_namespace: dbt_utils
    search_order: ["dbt_utils"]
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']
```

```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: dbt-labs/dbt_project_evaluator
    version: 0.12.2
```

### Steps to reproduce
`dbt run  --select=package:dbt_project_evaluator `
### Expected results
successful run

### Actual results
fail on creating stg_nodes table

### Screenshots and log output
<img width="792" alt="Screenshot 2024-08-16 at 1 22 16 PM" src="https://github.com/user-attachments/assets/e696136a-7f59-4473-baa8-d93c446fb40b">

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: dbt-labs/dbt_project_evaluator
    version: 0.12.2
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.15
  - latest:    1.8.5  - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 1.7.2  - Update available!
  - postgres: 1.7.15 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```
