### ISSUE TITLE
get_directory_pattern can falsely identify Windows machines as Mac / Linux

### ISSUE THREAD

**Issue by katieclaiborne-duet** [dbt-labs/dbt-project-evaluator#484]
### Describe the bug

If a Windows user has set their `HOME` environment variable to use forward slashes, the `get_directory_pattern` macro will falsely identify their machine as having a Mac / Linux operating system.

As a result, `int_all_graph_resources` will derive directory and file paths incorrectly, and dependent rules like `fct_source_directories` and `fct_model_directories` will return test failures.

### Steps to reproduce

- Initialize a dbt project and install project evaluator package
- On a Windows machine, set the `HOME` environment variable to use forward slashes
  - Note: I don't have a Windows machine myself, but am opening this issue on behalf of a teammate who does.
- Build project evaluator

### Expected results

In `int_all_graph_resources`, I expected `directory_path` to be populated, and `file_name` to contain the name of the file following the last path separator.

### Actual results

Instead, `directory_path` is a blank string, and `file_name` contains the unchanged `file_path` value.

#### int_all_graph_resources
<img width="912" alt="image" src="https://github.com/user-attachments/assets/33f3dae2-0301-4f6f-9bac-4828b6b5d75a">

#### fct_model_directories
<img width="923" alt="image" src="https://github.com/user-attachments/assets/27ec5b81-9acf-42de-b3b6-fdc7d686fde5">

### System information
**The contents of your `packages.yml` file:**
```yaml
packages:
  - package: dbt-labs/audit_helper
    version: 0.12.0

  - package: dbt-labs/codegen
    version: 0.12.1

  - package: dbt-labs/dbt_external_tables
    version: 0.9.0

  - package: dbt-labs/dbt_project_evaluator
    version: 0.12.2

  - package: dbt-labs/dbt_utils
    version: 1.2.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.5
  - latest:    1.8.5 - Up to date!

Plugins:
  - bigquery: 1.8.2 - Up to date!
```

### Are you interested in contributing the fix?

Yes, although I'd likely need some guidance!
