### ISSUE TITLE
Wrong is_freshness_enabled on stg_sources when warn_after is missing

### ISSUE THREAD

**Issue by cos-pet-learn** [dbt-labs/dbt-project-evaluator#520]
### Describe the bug

Sources are flaged with is_freshness_enabled = false when warn_after is not configured, but error_after is configured
### Steps to reproduce

I have configured freshness at source level:

```
version: 2

sources:
  - name: sdqn
    freshness:
      error_after:
        count: 168
        period: hour
``` 

### Expected results

is_freshness_enabled = true in stg_sources for all tables in that source
### Actual results

is_freshness_enabled = false in stg_sources for all tables in that source
### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```
versionless
