### ISSUE TITLE
Backticks cause false positive `is_empty_fct_hard_coded_references` error

### ISSUE THREAD

**Issue by shah204** [dbt-labs/dbt-project-evaluator#524]
### Describe the bug
Backticks cause false positive `is_empty_fct_hard_coded_references` error.

### Steps to reproduce
We had a model that included a commented out description, and in this description we used backticks. The package flagged these backticks as an example of a hard coded reference.

### Expected results
Backticks are not flagged.

### Actual results
Backticks seem to be read as a hard-coded reference.

### Screenshots and log output

<img width="688" alt="Image" src="https://github.com/user-attachments/assets/b229d6ee-ac09-4e3b-a547-a4da25822457" />
<img width="596" alt="Image" src="https://github.com/user-attachments/assets/b332b7e0-9dc3-49e7-87e3-e28fa6a81a15" />

### System information
**The contents of your `packages.yml` file:**

```
packages:
  #- package: dbt-labs/dbt_utils
  #  version: 1.1.0

  - package: dbt-labs/dbt_project_evaluator
    version: 0.14.2

  - package: dbt-labs/codegen
    version: 0.12.1

  # the tiktok_ads package adds dbt_utils, fivetran_utils, and
  # titktok_ads_source packages as dependencies so they can't
  # be listed twice in the package root directory.

  - package: fivetran/tiktok_ads
    version: 0.3.0

  - package: fivetran/zendesk
    version: 0.10.1

  - package: calogica/dbt_date
    version: [">=0.7.0", "<0.8.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.9
  - latest:    1.9.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 1.8.2 - Update available!
  - redshift: 1.8.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional context
N/A

### Are you interested in contributing the fix?
No
